// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvrMDONT_JKWvgO3YRPsAh5yMkz847e4',
    appId: '1:775656746417:android:c2de13f69dcc365d2a2190',
    messagingSenderId: '775656746417',
    projectId: 'efhmni-2b260',
    storageBucket: 'efhmni-2b260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfEifJIa7LPA1pNKdBVy5Ms5apI4sNbU',
    appId: '1:775656746417:ios:feb512d3312e00cf2a2190',
    messagingSenderId: '775656746417',
    projectId: 'efhmni-2b260',
    storageBucket: 'efhmni-2b260.firebasestorage.app',
    iosBundleId: 'net.codexeg.efhmni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqfEifJIa7LPA1pNKdBVy5Ms5apI4sNbU',
    appId: '1:775656746417:ios:feb512d3312e00cf2a2190',
    messagingSenderId: '775656746417',
    projectId: 'efhmni-2b260',
    storageBucket: 'efhmni-2b260.firebasestorage.app',
    iosBundleId: 'net.codexeg.efhmni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdg5cop09-FquaQuDLKT98F-lkL5vWPhk',
    appId: '1:775656746417:web:5a3a1629d443d5382a2190',
    messagingSenderId: '775656746417',
    projectId: 'efhmni-2b260',
    authDomain: 'efhmni-2b260.firebaseapp.com',
    storageBucket: 'efhmni-2b260.firebasestorage.app',
    measurementId: 'G-BR027QHMK5',
  );

}